__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [27]:
import numpy as np
from  numpy.linalg import eig
from  numpy.linalg import eigvals


A = np.array([[-1,-6],[2,6]])
u, v=eig(A)
print("u = ",u)
print("v = ",v)



u =  [2. 3.]
v =  [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [24]:
A@v

array([[-1.78885438,  2.49615088],
       [ 0.89442719, -1.66410059]])

In [26]:
u*v

array([[-1.78885438,  2.49615088],
       [ 0.89442719, -1.66410059]])

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$


$$\begin{pmatrix}
-x_{1}\\ 
-x_{2}
\end{pmatrix}
=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

При $$\lambda=-1$$ равеноство выполняется при любых $$\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}
$$
Таким образом любой вектор является собственным

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$


$$\begin{pmatrix}
2\\ 
2
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$


$$\lambda=2$$

In [31]:
import numpy as np
from  numpy.linalg import eig
from  numpy.linalg import eigvals


A = np.array([[1,1],[-1,3]])
v = np.array([1,1])


In [34]:
v1=A@v
v1

array([2, 2])

In [35]:
l = v1/v

In [36]:
l

array([2., 2.])

Таким образом, вектор  𝑥=(1,1)  является собственным вектором линейного оператора, заданного матрицей  𝐴 , и его собственное значение составляет  𝜆=2.

**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [41]:
import numpy as np
from  numpy.linalg import eig
from  numpy.linalg import eigvals


A = np.array([[0,3,0],[3,0,0],[0,0,3]])
v = np.array([3,-3,-4])

In [42]:
v1=A@v
v1

array([ -9,   9, -12])

In [43]:
l = v1/v
l

array([-3., -3.,  3.])

Таким образом, вектор  𝑥=(3,-3,-4)  является собственным вектором линейного оператора, заданного матрицей  𝐴 , и его собственное значение составляет  𝜆1=3,  𝜆2=-3,  𝜆1=-4.